### ISSUE TITLE
Move server project to example-server

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#112]
and provide an annotation and autoconfig for a server. This should make clear, that a user should create his own project in order to choose the interfaces he wants to support and provide configuration through property files.

An example of this tactics can be found here: https://github.com/codecentric/spring-boot-admin

**Comment by mweirauch** [comment]
Perhaps shove all examples/samples under a `factcast-samples` umbrella project?

**Comment by uweschaefer** [comment]
yes, that'd be even better.
