### ISSUE TITLE
fix verson and scope for slf4j-simple dep.

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#211]
as found by @mweirauch (THX!)
https://github.com/Mercateo/factcast/blob/issue98/factcast-internal-dep/pom.xml#L48

**Comment by uweschaefer** [comment]
looks like i was too excited about "refactoring into property" in idea to see that the leftover 5 was as unintended, as the version 1.7.2, where the 5 is actually kind of missing :D

**Comment by mweirauch** [comment]
Thanks. But isn't a new issue per feature branch (review) comment a bit overkill? ;)

**Comment by uweschaefer** [comment]
There is no extra branch for this. And issues - well - if i once have the time, it is nice to tick something off the TODO list...
