### ISSUE TITLE
Sanitize properties

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#212]
**Is your feature request related to a problem? Please describe.**
currently, properties are not consistent with the projects, they belong to (`factcast.pg`). As a preparation for 0.2, this should be sanitized.

Note that the migration needs to be documented

**Comment by uweschaefer** [comment]
see issue212

**Comment by uweschaefer** [comment]
see factcast-site/documentation/content/migration-0.2.md as a place to add documentation

**Comment by uweschaefer** [comment]
probably done?

**Comment by mweirauch** [comment]
IIRC this was about the naming: `factcast.pg.someprop` -> `factcast.store.postgresql.someprop`.

**Comment by uweschaefer** [comment]
ah, ok. reopening.

**Comment by uweschaefer** [comment]
do you want to work on that or shall i try?
asking because core team is pushy about releasing a 0.1.0 soon.

**Comment by mweirauch** [comment]
No time for that (right now). Can be broken later, though.

**Comment by uweschaefer** [comment]
closed by #403
