### ISSUE TITLE
store-pgsql: move auto-configuration out of module

### ISSUE THREAD

**Issue by mweirauch** [Mercateo/factcast#214]
**Is your feature request related to a problem? Please describe.**
The auto-configuration classes should be part of `factcast-spring-boot-autoconfigure` so that `factcast-store-pgsql` is "Spring Boot free".

**Describe the solution you'd like**
See above. Here the configuration properties class should stay in the module though and it can be made a `@ConfigurationProperties` bean in a factory.

Could/should be done before #212.

**Comment by uweschaefer** [comment]
probably included in #310
