### ISSUE TITLE
Document good settings for keepalive behaviour

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#272]
see https://github.com/Mercateo/factcast/pull/271

```
grpc.client.factstore.enable-keep-alive=true
grpc.client.factstore.keep-alive-time=360
grpc.client.factstore.keep-alive-without-calls=true
```

could be a good start, but we have to investigate.

**Comment by uweschaefer** [comment]
@nln42 i'd be happy get a PR or hints here

**Comment by nln42** [comment]
client side
```
grpc.client.factstore.enable-keep-alive=true
grpc.client.factstore.keep-alive-time=310
grpc.client.factstore.keep-alive-without-calls=true
```

server side (since factcast-0.1.0-M1)
```
grpc.server.permit-keep-alive-without-calls=true
grpc.server.permit-keep-alive-time=10
```

Will be documented.

**Comment by uweschaefer** [comment]
yes, please! appreciated.

**Comment by uweschaefer** [comment]
Oh, just recognized the "permit-keep-alive-time", interesting.

**Comment by uweschaefer** [comment]
i there anything i can help with?

**Comment by nln42** [comment]
How to change the order of the pages in the main navigation to the left?
Expected theres only the need to change the value of "weight", but didn't work...

see :  issue#272_document_good_settings_for_keepalive

**Comment by uweschaefer** [comment]
as it turns out, the weight (now) belongs in the top level section of the page header, not in the menu section...
i fixed the weight and sorted the pages in this section. if you agree please merge the PR

**Comment by nln42** [comment]
nice - thx a lot

**Comment by Mortinke** [comment]
In the [documentation](https://docs.factcast.org/setup/examples/grpc-config-keepalive/) is still the old value 300 for the client side

**Comment by uweschaefer** [comment]
yes. i don't think it is a bad. did you set grpc.server.permit-keep-alive-time?

@nln42 can probably explain the details. if you still think it shoul dbe changed, please provide a PR and convince @nln42 to review it :)

**Comment by Mortinke** [comment]
We are currently setting it for all applications 👍
