### ISSUE TITLE
InMem FactCast doesn't support lastKnownEventId

### ISSUE THREAD

**Issue by StephanPraetsch** [Mercateo/factcast#307]
**Describe the bug**
If I use InMem FactStore and call it with lastKnownEventId then I always get every event instead of only new events.

**FactCast Server/Client Version**
0.0.34

**To Reproduce**
```
        eventStore.subscribeToFacts(
                SubscriptionRequest.catchup(factsOfInterest).from(lastFactConsumed.get()), this)
                .awaitComplete();
```

**Expected behavior**
I only receive events that are after lastKnownEventId.

**Additional context**
...

**Comment by uweschaefer** [comment]
thx for finding/reporting

**Comment by StephanPraetsch** [comment]
Umm, some strange behavior I've seen

a) publish new events every 5s and pulling every 1s => I receive events multiple time
b) publish new events every 5s but pulling every 9s => I receive events only once

As far as I could see it's all fine even when pull and push interval is identical (5s for instance). Only if I pull more often than I publish I receive events multiple times.

**Comment by uweschaefer** [comment]
would it be possible to contribute a testcase that shows the problem? (it'd be easier to fix, then :D)

**Comment by StephanPraetsch** [comment]
there you go https://github.com/StephanPraetsch/factcast-inmem-problem

**Comment by uweschaefer** [comment]
thanks. not exactly a what i had in mind, though...

i was thinking of a junit testcase :D

**Comment by uweschaefer** [comment]
you are confusing IDs.

**Comment by uweschaefer** [comment]
or maybe you are not and i am. need some more time...

i added a line to compare the Fact you recieve to the Event you process, something like:

```
public void onNext(@NonNull Fact f) {
        log.info("consuming " + f.ns() + " " + f.type() + " " + f.id());
        UserCreated event = toEvent(f);
        log.info("comparing Events: " + f.toString() + "\n\nvs\n"+event);
```
output for instance:
```
2019-03-10 17:12:50.766  INFO 26911 --- [pool-1-thread-1] com.example.my.ReadModel                 : comparing Events: {
  "jsonHeader" : "{\"ns\":\"user\",\"aggIds\":[\"06349409-3434-4c76-8273-ee4869ac03b5\"],\"id\":\"dd5ca37c-7805-4774-8a03-4716eeb4bb4e\",\"type\":\"UserCreated\",\"meta\":{\"_ser\":1}}",
  "jsonPayload" : "{\"id\":\"06349409-3434-4c76-8273-ee4869ac03b5\",\"name\":\"2019-03-10T17:12:49.779+01:00\"}"
}

vs

UserCreated(id=06349409-3434-4c76-8273-ee4869ac03b5, name=2019-03-10T17:12:49.779+01:00)
```
what you see here, is that you use the id within the events payload to identify the *Fact* which is wrong as the have nothing to do with each other.

**Comment by uweschaefer** [comment]
diggin...

**Comment by uweschaefer** [comment]
looks like there is in fact something broken in InMemFS. i'll add some tests.

**Comment by uweschaefer** [comment]
Good catch! In fact the problem only arises, if catchup does not find any Fact. So your observation was right to see a connection between publishing frequency and catchup confusion.

added tests accordingly. please validate the current behavior, and approve the PR.
