### ISSUE TITLE
Unify autoconfiguration

### ISSUE THREAD

**Issue by uweschaefer** [Mercateo/factcast#310]
**Is your feature request related to a problem? Please describe.**
Make sure all Autoconfiguration is moved to the designated module.

For instance client-grpc seems to have an autoconfiguration left.

**Comment by mweirauch** [comment]
This one will be fun: https://github.com/Mercateo/factcast/blob/master/factcast-store-pgsql/src/main/resources/META-INF/spring.factories ;)

**Comment by uweschaefer** [comment]
well, you're to blame: you made me :D

**Comment by uweschaefer** [comment]
@mweirauch  do you mind reviewing this, if you have time?
not pressing...

**Comment by uweschaefer** [comment]
not yet ready for review, i'll opena another one when it is.
