### ISSUE TITLE
Introduce Locks

### ISSUE THREAD

**Issue by JoergAdler** [Mercateo/factcast#43]
For consistent writing, one needs a centralized lock, managed from the fact-cast server.

**Comment by uweschaefer** [comment]
Discuss: Is this really the right place to offer such a thing?

**Comment by OOlsen** [comment]
After a short brainstorming with @uweschaefer, the grpc lock interface could look something like this:

```
message MSG_LOCK{
	MSG_UUID uuid = 1;
}
message MSG_RESULT{
	bool success=1;
}
service RemoteFactStoreWithLocks{
	rpc lock(stream MSG_LOCK) returns (MSG_RESULT){}
```

The server holds the lock as long as the client sends a periodical keep-alive.

**Comment by uweschaefer** [comment]
will close this for now in favor of optimistic locking #239
