### ISSUE TITLE
Integration Test

### ISSUE THREAD

**Issue by StephanPraetsch** [Mercateo/factcast#447]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have a SpringBoot application without an integration test that covers some general behavior.

**Describe the solution you'd like**
I'd like to know a sensible way how to write an integration test that uses my productive FactCast (same libs and same configuration). For instance I'd like to test
  * Does the application start at all?
  * Does GRPC work with the expected port?
  * Will I receive a just published event?
 
Therefor I think that test must run with a PostgreSQL (instead of a InMemFactstore).

**Comment by uweschaefer** [comment]
We talked and agreed this is an issue of documentation:

it'd be nice to have a page in factcast-site that walks a user through setting up an integration test that uses testcontainer to run a pgsql and a factcast with pgsql-store before running an integration test.

@StephanPraetsch would you mind writing one?
