### ISSUE TITLE
EnableAutoConfiguration = FactCastRestConfiguration broken?

### ISSUE THREAD

**Issue by nln42** [Mercateo/factcast#83]
factcast-server-rest-0.0.6.jar\META-INF\spring.factories:

`org.springframework.boot.autoconfigure.EnableAutoConfiguration=org.factcast.server.rest.FactCastRestConfiguration`

needed to give Spring's ComponentScan a little hint in order to get the expected response from web endpoint's root - so auto configuration seems broken

```
@SpringBootApplication
@ComponentScan(basePackageClasses = { FactCastRestApplication.class })
public class SomeSpringBootApplicationUsingFactCastServerRest{
...
}
```

(edit) : using spring-boot.version 2.0.4.RELEASE

**Comment by uweschaefer** [comment]
@nln42 ?

**Comment by uweschaefer** [comment]
closing this as #78 will take care of this. feel free to re-open, if still relevant.
